name: ngrok
services:
  ngrok:
    command:
      - http
      - --domain=xxxxx.ngrok-free.app
      - "80"
    container_name: ngrok
    deploy:
      resources:
        limits:
          memory: 256M
    environment:
      - NGROK_AUTHTOKEN=xxxxx
    image: ngrok/ngrok
    privileged: true
    restart: unless-stopped
    x-casaos:
      envs:
        - container: NGROK_AUTHTOKEN
          description:
            en_us: "NGROK_AUTHTOKEN = set our own token"
    ports: []
    volumes: []
    devices: []
    cap_add: []
    network_mode: host
x-casaos:
  architectures:
    - "386"
    - arm
    - arm64
    - amd64
    - ppc64le
  author: sakibweb
  category: Network
  description:
    en_us: "Ngrok is a secure unified ingress platform that combines your global server load balancing, reverse proxy, firewall, API gateway and Kubernetes Ingress Controller to deliver applications and APIs."
  developer: NgrokTeam
  hostname: xxxxx.ngrok-free.app
  icon: https://cdn.jsdelivr.net/gh/sakibweb/CasaOS-SakibWeb@main/App/Ngrok/icon.png
  index: /
  main: ngrok
  port_map: ""
  scheme: http
  store_app_id: ngrok
  tagline:
    en_us: "Ngrok is a secure unified ingress platform that combines your global server load balancing, reverse proxy, firewall, API gateway and Kubernetes Ingress Controller to deliver applications and APIs."
  thumbnail: https://cdn.jsdelivr.net/gh/sakibweb/CasaOS-SakibWeb@main/App/Ngrok/thumbnail.png
  screenshot_link:
    - https://github.com/sakibweb/CasaOS-SakibWeb/blob/main/App/Ngrok/screenshot.png
  tips:
    custom: |-
      Environment Variables
      NGROK_AUTHTOKEN = set our own
      - - - - - - - - - - - - - - - - - - - - - - 
      Container Command
      http / https
      your ngrok domain
      your port for forwarding
      - - - - - - - - - - - - - - - - - - - - - - 
      Hostname / Web UI = your subdomain
  title:
    custom: ""
    en_us: Ngrok
