name: vigorous_felice
services:
  main_app:
    cpu_shares: 50
    command:
      - http
      - --domain=robin-informed-bluebird.ngrok-free.app
      - "80"
    container_name: ngrok
    deploy:
      resources:
        limits:
          memory: 512M
    environment:
      - NGROK_AUTHTOKEN=1bkytgmw1t404YEerkWfYFsOvir_3GyVpun5pjpAPVR4fGTH1
    image: ngrok/ngrok
    labels:
      icon: https://cdn.jsdelivr.net/gh/sakibweb/CasaOS-SakibWeb@main/App/Ngrok/icon.png
    restart: unless-stopped
    ports: []
    volumes: []
    devices: []
    cap_add: []
    network_mode: host
    privileged: false
x-casaos:
  author: self
  category: self
  hostname: robin-informed-bluebird.ngrok-free.app
  icon: https://cdn.jsdelivr.net/gh/sakibweb/CasaOS-SakibWeb@main/App/Ngrok/icon.png
  index: /
  port_map: ""
  scheme: http
  store_app_id: vigorous_felice
  tips:
    custom: |-2
            Environment Variables
            NGROK_AUTHTOKEN = set our own
            - - - - - - - - - - - - - - - - - -
            Container Command
            http / https
            your ngrok domain
            your port for forwarding
            - - - - - - - - - - - - - - - - - -
            Hostname / Web UI = your subdomain
  title:
    custom: Ngrok
