name: vigorous_felice

services:
  main_app:
    cpu_shares: 50
    command:
      - http
      - --domain=xxxxx.ngrok-free.app
      - "80"
    container_name: ngrok
    deploy:
      resources:
        limits:
          memory: 512M
    environment:
      - NGROK_AUTHTOKEN=xxxxx
    image: ngrok/ngrok
    labels:
      icon: https://cdn.jsdelivr.net/gh/sakibweb/CasaOS-SakibWeb@main/App/Ngrok/icon.png
    restart: unless-stopped
    ports: []
    volumes: []
    devices: []
    cap_add: []
    network_mode: host
    privileged: false

x-casaos:
  author: self
  category: Network
  hostname: xxxxx.ngrok-free.app
  icon: https://cdn.jsdelivr.net/gh/sakibweb/CasaOS-SakibWeb@main/App/Ngrok/icon.png
  index: /
  port_map: ""
  scheme: http
  store_app_id: vigorous_felice
  tips:
    custom: |-2
      Environment Variables
      NGROK_AUTHTOKEN = set your own
      - - - - - - - - - - - - - - - - - -
      Container Command
      http / https
      your ngrok domain
      your port for forwarding
      - - - - - - - - - - - - - - - - - -
      Hostname / Web UI = your subdomain
  title:
    custom: Ngrok
  tagline: "Secure unified ingress platform for global server load balancing, reverse proxy, firewall, API gateway, and Kubernetes Ingress Controller."
  overview: "Ngrok is a secure unified ingress platform that combines your global server load balancing, reverse proxy, firewall, API gateway, and Kubernetes Ingress Controller to deliver applications and APIs."
  thumbnail: https://cdn.jsdelivr.net/gh/sakibweb/CasaOS-SakibWeb@main/App/Ngrok/thumbnail.png
  screenshots:
    - https://cdn.jsdelivr.net/gh/sakibweb/CasaOS-SakibWeb@main/App/Ngrok/screenshot-1.png
